export interface FormField {
  name: string;
  label: string;
  type: "text" | "textarea" | "select" | "number";
  placeholder?: string;
  required: boolean;
  options?: string[];
  maxLength?: number;
}

export interface ToolConfig {
  slug: string;
  name: string;
  shortDescription: string;
  longDescription: string;
  category: string;
  icon: string;
  seoTitle: string;
  seoDescription: string;
  seoKeywords: string[];
  fields: FormField[];
  systemPrompt: string;
}

export const tools: ToolConfig[] = [
  {
    slug: "ai-cold-email-writer",
    name: "AI Cold Email Writer",
    shortDescription: "Generate personalized cold emails that actually get replies.",
    longDescription: "Write compelling cold outreach emails personalized to your prospect. AI analyzes your offer and target to create emails that land in inboxes and get responses.",
    category: "Sales",
    icon: "\u2709\ufe0f",
    seoTitle: "Free AI Cold Email Writer \u2014 Generate Personalized Outreach | BizToolbox AI",
    seoDescription: "Write cold emails that get replies. AI generates personalized outreach emails for sales, partnerships, and business development. Free tool.",
    seoKeywords: ["cold email generator", "AI email writer", "sales email template", "outreach email generator"],
    fields: [
      { name: "yourOffer", label: "What You\u2019re Offering", type: "textarea", placeholder: "Describe your product/service and key benefits", required: true },
      { name: "targetPerson", label: "Who You\u2019re Emailing", type: "textarea", placeholder: "Their role, company, industry", required: true },
      { name: "tone", label: "Tone", type: "select", options: ["Professional", "Casual", "Friendly", "Direct"], required: true },
      { name: "cta", label: "Desired Call-to-Action", type: "text", placeholder: "e.g., Book a 15-min call", required: true },
      { name: "personalDetail", label: "Personal Detail (optional)", type: "text", placeholder: "Something specific about them", required: false },
    ],
    systemPrompt: "You are an elite cold email copywriter who has written campaigns with 40%+ open rates. Write a cold email that: 1) Has a subject line under 6 words that creates curiosity without being clickbait, 2) Opens with something about THEM, not you, 3) Establishes credibility in one sentence, 4) Clearly states the value proposition, 5) Includes a low-friction CTA, 6) Is under 150 words, 7) Sounds human, not AI-generated. Provide 3 email variations: a) The Curiosity Opener, b) The Value-First Approach, c) The Mutual Connection Style.",
  },
  {
    slug: "ai-return-refund-policy-generator",
    name: "AI Return & Refund Policy Generator",
    shortDescription: "Create professional return policies in seconds.",
    longDescription: "Generate legally-informed return and refund policies tailored to your business type. Covers all standard scenarios and protects your business.",
    category: "Legal",
    icon: "\ud83d\udcdc",
    seoTitle: "Free AI Return & Refund Policy Generator | BizToolbox AI",
    seoDescription: "Create a professional return and refund policy for your business in seconds. AI generates customized policies for e-commerce, SaaS, and services. Free tool.",
    seoKeywords: ["return policy generator", "refund policy template", "AI policy writer"],
    fields: [
      { name: "businessName", label: "Business Name", type: "text", placeholder: "Your company name", required: true },
      { name: "businessType", label: "Business Type", type: "select", options: ["E-commerce", "SaaS", "Service", "Digital Products", "Subscription"], required: true },
      { name: "returnWindow", label: "Return Window (days)", type: "number", placeholder: "30", required: true },
      { name: "refundMethod", label: "Refund Method", type: "select", options: ["Full refund", "Store credit", "Exchange only", "Partial refund"], required: true },
    ],
    systemPrompt: "You are a business policy expert. Generate a professional return and refund policy that: 1) Is clear and customer-friendly, 2) Covers standard scenarios, 3) Protects the business legally, 4) Includes eligibility conditions, 5) Describes the refund process step by step, 6) Addresses exceptions. Note: This is AI-generated and should be reviewed by a legal professional.",
  },
  {
    slug: "ai-business-plan-generator",
    name: "AI Business Plan Generator",
    shortDescription: "Create a comprehensive business plan outline instantly.",
    longDescription: "Generate a structured business plan with executive summary, market analysis, and financial projections. Perfect for startups seeking funding.",
    category: "Sales",
    icon: "\ud83d\udcca",
    seoTitle: "Free AI Business Plan Generator \u2014 Create Plans in Minutes | BizToolbox AI",
    seoDescription: "Generate a professional business plan instantly. AI creates structured plans with market analysis, financial projections, and strategy. Free tool.",
    seoKeywords: ["business plan generator", "AI business plan", "startup plan template"],
    fields: [
      { name: "businessName", label: "Business Name", type: "text", placeholder: "Your company name", required: true },
      { name: "industry", label: "Industry", type: "text", placeholder: "e.g., SaaS, E-commerce, Healthcare", required: true },
      { name: "problem", label: "Problem You Solve", type: "textarea", placeholder: "What pain point does your business address?", required: true },
      { name: "solution", label: "Your Solution", type: "textarea", placeholder: "How does your product/service solve this?", required: true },
      { name: "targetMarket", label: "Target Market", type: "text", placeholder: "Who are your ideal customers?", required: true },
      { name: "revenueModel", label: "Revenue Model", type: "select", options: ["Subscription", "One-time purchase", "Freemium", "Marketplace", "Advertising"], required: true },
    ],
    systemPrompt: "You are a startup advisor who has helped 500+ companies create business plans. Generate a comprehensive business plan that includes: 1) Executive Summary, 2) Problem & Solution, 3) Market Analysis, 4) Business Model, 5) Marketing Strategy, 6) Financial Projections (Year 1-3), 7) Team Requirements, 8) Key Milestones. Make it specific, data-informed, and investor-ready.",
  },
  {
    slug: "ai-invoice-generator",
    name: "AI Invoice Generator",
    shortDescription: "Create professional invoices with proper formatting.",
    longDescription: "Generate clean, professional invoices with all required fields. Includes tax calculations, payment terms, and professional formatting.",
    category: "Sales",
    icon: "\ud83e\uddfe",
    seoTitle: "Free AI Invoice Generator \u2014 Professional Invoices in Seconds | BizToolbox AI",
    seoDescription: "Create professional invoices instantly. AI generates formatted invoices with tax calculations, payment terms, and line items. Free tool.",
    seoKeywords: ["invoice generator", "free invoice maker", "AI invoice template"],
    fields: [
      { name: "businessName", label: "Your Business Name", type: "text", required: true },
      { name: "clientName", label: "Client Name", type: "text", required: true },
      { name: "items", label: "Items/Services", type: "textarea", placeholder: "List items with quantities and prices, one per line", required: true },
      { name: "paymentTerms", label: "Payment Terms", type: "select", options: ["Due on receipt", "Net 15", "Net 30", "Net 60"], required: true },
      { name: "taxRate", label: "Tax Rate (%)", type: "number", placeholder: "0", required: false },
    ],
    systemPrompt: "You are a financial document specialist. Generate a clean, professional invoice in markdown format that includes: 1) Invoice number (generate one), 2) Date and due date, 3) From/To details, 4) Itemized list with quantities and prices, 5) Subtotal, tax, and total, 6) Payment terms and instructions. Format it clearly for easy reading.",
  },
  {
    slug: "ai-social-media-bio-generator",
    name: "AI Social Media Bio Generator",
    shortDescription: "Create compelling bios for any social platform.",
    longDescription: "Generate optimized bios for LinkedIn, Twitter, Instagram, and more. AI crafts bios that capture attention and drive engagement.",
    category: "Marketing",
    icon: "\ud83d\udcf1",
    seoTitle: "Free AI Social Media Bio Generator \u2014 All Platforms | BizToolbox AI",
    seoDescription: "Create perfect social media bios for LinkedIn, Twitter, Instagram, and more. AI generates platform-optimized bios that stand out. Free tool.",
    seoKeywords: ["social media bio generator", "LinkedIn bio writer", "Instagram bio generator"],
    fields: [
      { name: "name", label: "Name or Business Name", type: "text", required: true },
      { name: "platform", label: "Platform", type: "select", options: ["LinkedIn", "Twitter/X", "Instagram", "TikTok", "Facebook", "YouTube"], required: true },
      { name: "role", label: "What You Do", type: "text", placeholder: "Your role or business description", required: true },
      { name: "personality", label: "Personality/Tone", type: "select", options: ["Professional", "Creative", "Witty", "Inspirational", "Casual"], required: true },
      { name: "keyPoints", label: "Key Things to Mention", type: "textarea", placeholder: "Achievements, interests, specialties", required: false },
    ],
    systemPrompt: "You are a social media branding expert. Generate 5 bio variations for the specified platform that: 1) Fit within platform character limits, 2) Include relevant keywords, 3) Have a clear value proposition, 4) Match the desired personality, 5) Include a CTA where appropriate. For each bio, note why it works and what makes it effective.",
  },

    // Tool 6: Employee Offer Letter Generator
  {
    slug: "employee-offer-letter-generator",
    name: "AI Employee Offer Letter Generator",
    shortDescription: "Create professional job offer letters instantly.",
    longDescription: "Generate comprehensive offer letters with compensation details, start dates, and company information.",
    category: "HR",
    icon: "\ud83d\udcdd",
    seoTitle: "Free AI Employee Offer Letter Generator | BizToolbox AI",
    seoDescription: "Create professional job offer letters instantly. AI generates formatted offer letters with all essential details.",
    seoKeywords: ["offer letter generator", "employee offer letter template", "job offer letter maker"],
    fields: [
      { name: "companyName", label: "Company Name", type: "text", required: true },
      { name: "candidateName", label: "Candidate Name", type: "text", required: true },
      { name: "position", label: "Job Title", type: "text", required: true },
      { name: "salary", label: "Salary/Compensation", type: "text", required: true },
      { name: "startDate", label: "Start Date", type: "text", required: true },
      { name: "benefits", label: "Benefits & Perks", type: "textarea", placeholder: "Health insurance, PTO, etc.", required: false },
    ],
    systemPrompt: "You are an HR specialist. Generate a professional, warm offer letter that includes: 1) Congratulations, 2) Position and reporting structure, 3) Compensation and benefits, 4) Start date and logistics, 5) Acceptance deadline. Use professional but welcoming tone.",
  },
  // Tool 7: Meeting Agenda Generator
  {
    slug: "meeting-agenda-generator",
    name: "AI Meeting Agenda Generator",
    shortDescription: "Create structured meeting agendas in seconds.",
    longDescription: "Generate organized meeting agendas with time allocations, discussion topics, and action items.",
    category: "Communication",
    icon: "\ud83d\udcc5",
    seoTitle: "Free AI Meeting Agenda Generator | BizToolbox AI",
    seoDescription: "Create professional meeting agendas instantly with time allocations and discussion topics.",
    seoKeywords: ["meeting agenda generator", "agenda template", "meeting planner"],
    fields: [
      { name: "meetingType", label: "Meeting Type", type: "select", options: ["Team Standup", "Board Meeting", "Client Meeting", "Project Kickoff", "Brainstorming", "Performance Review", "All-Hands"], required: true },
      { name: "duration", label: "Duration (minutes)", type: "number", placeholder: "60", required: true },
      { name: "topics", label: "Key Topics", type: "textarea", placeholder: "List the main discussion points", required: true },
      { name: "attendees", label: "Attendees", type: "text", placeholder: "Number or names of attendees", required: false },
    ],
    systemPrompt: "You are a meeting facilitator. Create a well-structured agenda with: 1) Time allocations per topic, 2) Clear objectives, 3) Discussion points, 4) Action items section, 5) Next steps. Format in markdown.",
  },
  // Tool 8: SWOT Analysis Generator
  {
    slug: "swot-analysis-generator",
    name: "AI SWOT Analysis Generator",
    shortDescription: "Generate comprehensive SWOT analyses for any business.",
    longDescription: "Create detailed Strengths, Weaknesses, Opportunities, and Threats analyses for strategic planning.",
    category: "Strategy",
    icon: "\ud83d\udcca",
    seoTitle: "Free AI SWOT Analysis Generator | BizToolbox AI",
    seoDescription: "Generate detailed SWOT analyses for your business instantly. AI-powered strategic planning tool.",
    seoKeywords: ["SWOT analysis generator", "SWOT template", "business strategy tool"],
    fields: [
      { name: "businessName", label: "Business Name", type: "text", required: true },
      { name: "industry", label: "Industry", type: "text", required: true },
      { name: "description", label: "Business Description", type: "textarea", placeholder: "What does your business do?", required: true },
      { name: "competitors", label: "Key Competitors", type: "text", placeholder: "Main competitors", required: false },
    ],
    systemPrompt: "You are a business strategy consultant. Create a detailed SWOT analysis with: 1) 5+ Strengths, 2) 5+ Weaknesses, 3) 5+ Opportunities, 4) 5+ Threats. Include actionable insights for each point. Format in a clear markdown table.",
  },
  // Tool 9: Product Description Writer
  {
    slug: "product-description-writer",
    name: "AI Product Description Writer",
    shortDescription: "Write compelling product descriptions that sell.",
    longDescription: "Generate SEO-optimized product descriptions for e-commerce, catalogs, and marketing materials.",
    category: "Marketing",
    icon: "\ud83d\udee0\ufe0f",
    seoTitle: "Free AI Product Description Writer | BizToolbox AI",
    seoDescription: "Write compelling product descriptions that convert. AI generates SEO-optimized copy for any product.",
    seoKeywords: ["product description writer", "product copywriter AI", "e-commerce description generator"],
    fields: [
      { name: "productName", label: "Product Name", type: "text", required: true },
      { name: "features", label: "Key Features", type: "textarea", placeholder: "List the main features and specs", required: true },
      { name: "targetAudience", label: "Target Audience", type: "text", placeholder: "Who is this product for?", required: true },
      { name: "tone", label: "Tone", type: "select", options: ["Professional", "Casual", "Luxury", "Fun", "Technical"], required: true },
      { name: "platform", label: "Platform", type: "select", options: ["Website", "Amazon", "Shopify", "Etsy", "General"], required: true },
    ],
    systemPrompt: "You are an expert e-commerce copywriter. Write a compelling product description that: 1) Hooks with benefits first, 2) Highlights key features, 3) Addresses pain points, 4) Includes sensory language, 5) Ends with a CTA. Optimize for the specified platform.",
  },
  // Tool 10: Thank You Email Writer
  {
    slug: "thank-you-email-writer",
    name: "AI Thank You Email Writer",
    shortDescription: "Write professional thank you emails for any occasion.",
    longDescription: "Generate thoughtful thank you emails for interviews, clients, referrals, and business occasions.",
    category: "Communication",
    icon: "\ud83d\ude4f",
    seoTitle: "Free AI Thank You Email Writer | BizToolbox AI",
    seoDescription: "Write professional thank you emails instantly. Perfect for post-interview, client, and business occasions.",
    seoKeywords: ["thank you email generator", "professional thank you letter", "business thank you email"],
    fields: [
      { name: "occasion", label: "Occasion", type: "select", options: ["Job Interview", "Client Meeting", "Referral", "Gift/Favor", "Partnership", "Event Attendance", "Purchase"], required: true },
      { name: "recipientName", label: "Recipient Name", type: "text", required: true },
      { name: "context", label: "Context/Details", type: "textarea", placeholder: "What are you thanking them for?", required: true },
      { name: "senderName", label: "Your Name", type: "text", required: true },
    ],
    systemPrompt: "You are a professional communication expert. Write a sincere, well-crafted thank you email that: 1) Opens with genuine gratitude, 2) References specific details, 3) Highlights the value/impact, 4) Looks forward to the future, 5) Closes warmly. Keep it concise.",
  },
  // Tool 11-20 batch
  {
    slug: "privacy-policy-generator",
    name: "AI Privacy Policy Generator",
    shortDescription: "Generate GDPR-compliant privacy policies.",
    longDescription: "Create comprehensive privacy policies covering data collection, usage, storage, and user rights.",
    category: "Legal",
    icon: "\ud83d\udd12",
    seoTitle: "Free AI Privacy Policy Generator | BizToolbox AI",
    seoDescription: "Generate comprehensive privacy policies for your website or app. GDPR and CCPA compliant.",
    seoKeywords: ["privacy policy generator", "GDPR privacy policy", "free privacy policy maker"],
    fields: [
      { name: "businessName", label: "Business/Website Name", type: "text", required: true },
      { name: "websiteUrl", label: "Website URL", type: "text", required: true },
      { name: "dataCollected", label: "Data Collected", type: "textarea", placeholder: "Email, name, payment info, cookies, etc.", required: true },
      { name: "businessType", label: "Business Type", type: "select", options: ["SaaS", "E-commerce", "Blog/Content", "Mobile App", "Service Business"], required: true },
    ],
    systemPrompt: "You are a legal document specialist. Generate a comprehensive privacy policy that covers: 1) Information collected, 2) How data is used, 3) Data sharing practices, 4) Data security, 5) User rights (GDPR/CCPA), 6) Cookie policy, 7) Contact information.",
  },
  {
    slug: "terms-of-service-generator",
    name: "AI Terms of Service Generator",
    shortDescription: "Create professional terms of service documents.",
    longDescription: "Generate comprehensive ToS covering user agreements, liability, and intellectual property.",
    category: "Legal",
    icon: "\ud83d\udcc4",
    seoTitle: "Free AI Terms of Service Generator | BizToolbox AI",
    seoDescription: "Create professional terms of service for your website or app.",
    seoKeywords: ["terms of service generator", "ToS generator", "terms and conditions maker"],
    fields: [
      { name: "businessName", label: "Business Name", type: "text", required: true },
      { name: "websiteUrl", label: "Website/App URL", type: "text", required: true },
      { name: "serviceDescription", label: "Service Description", type: "textarea", required: true },
      { name: "hasPayments", label: "Accepts Payments?", type: "select", options: ["Yes", "No"], required: true },
    ],
    systemPrompt: "You are a legal document specialist. Generate comprehensive Terms of Service covering: 1) Acceptance of terms, 2) Service description, 3) User responsibilities, 4) Intellectual property, 5) Limitation of liability, 6) Termination, 7) Governing law.",
  },
  {
    slug: "blog-post-outline-generator",
    name: "AI Blog Post Outline Generator",
    shortDescription: "Create SEO-optimized blog post outlines.",
    longDescription: "Generate structured blog post outlines with headings, key points, and SEO suggestions.",
    category: "Marketing",
    icon: "\u270d\ufe0f",
    seoTitle: "Free AI Blog Post Outline Generator | BizToolbox AI",
    seoDescription: "Create comprehensive blog post outlines with headings and key points.",
    seoKeywords: ["blog outline generator", "content outline tool", "blog post planner"],
    fields: [
      { name: "topic", label: "Blog Topic", type: "text", required: true },
      { name: "targetKeyword", label: "Target Keyword", type: "text", required: true },
      { name: "audience", label: "Target Audience", type: "text", required: true },
      { name: "wordCount", label: "Target Word Count", type: "select", options: ["500-800", "800-1200", "1200-2000", "2000+"], required: true },
    ],
    systemPrompt: "You are an SEO content strategist. Create a detailed blog post outline with: 1) SEO-optimized title options, 2) Meta description, 3) H2/H3 headings structure, 4) Key points per section, 5) CTA placement. Target the specified keyword.",
  },
  {
    slug: "elevator-pitch-generator",
    name: "AI Elevator Pitch Generator",
    shortDescription: "Craft compelling 30-second elevator pitches.",
    longDescription: "Generate concise, persuasive elevator pitches for your business, product, or idea.",
    category: "Sales",
    icon: "\ud83c\udfaf",
    seoTitle: "Free AI Elevator Pitch Generator | BizToolbox AI",
    seoDescription: "Create compelling elevator pitches in seconds. Perfect for networking and investors.",
    seoKeywords: ["elevator pitch generator", "business pitch maker", "30 second pitch"],
    fields: [
      { name: "businessName", label: "Business/Product Name", type: "text", required: true },
      { name: "problem", label: "Problem You Solve", type: "textarea", required: true },
      { name: "solution", label: "Your Solution", type: "textarea", required: true },
      { name: "audience", label: "Pitch Audience", type: "select", options: ["Investors", "Customers", "Partners", "Networking", "Job Interview"], required: true },
    ],
    systemPrompt: "You are a pitch coach. Create 3 elevator pitch variations (15, 30, and 60 seconds) that: 1) Hook with the problem, 2) Present the solution, 3) Highlight unique value, 4) End with a call to action.",
  },
  {
    slug: "customer-persona-generator",
    name: "AI Customer Persona Generator",
    shortDescription: "Build detailed customer personas for marketing.",
    longDescription: "Generate comprehensive buyer personas with demographics, goals, and pain points.",
    category: "Marketing",
    icon: "\ud83d\udc64",
    seoTitle: "Free AI Customer Persona Generator | BizToolbox AI",
    seoDescription: "Build detailed customer personas instantly. AI generates demographics, goals, and behavior patterns.",
    seoKeywords: ["customer persona generator", "buyer persona template", "target audience tool"],
    fields: [
      { name: "businessName", label: "Business Name", type: "text", required: true },
      { name: "product", label: "Product/Service", type: "text", required: true },
      { name: "industry", label: "Industry", type: "text", required: true },
      { name: "currentCustomers", label: "Describe Your Customers", type: "textarea", required: false },
    ],
    systemPrompt: "You are a marketing researcher. Create 2 detailed buyer personas including: 1) Name and demographics, 2) Job and income, 3) Goals and motivations, 4) Pain points, 5) Preferred channels, 6) Buying behavior, 7) Objections.",
  },
  {
    slug: "job-description-generator",
    name: "AI Job Description Generator",
    shortDescription: "Write compelling job descriptions that attract talent.",
    longDescription: "Generate professional job postings with responsibilities, requirements, and culture sections.",
    category: "HR",
    icon: "\ud83d\udcbc",
    seoTitle: "Free AI Job Description Generator | BizToolbox AI",
    seoDescription: "Write professional job descriptions that attract top talent.",
    seoKeywords: ["job description generator", "job posting writer", "hiring template"],
    fields: [
      { name: "jobTitle", label: "Job Title", type: "text", required: true },
      { name: "department", label: "Department", type: "text", required: true },
      { name: "level", label: "Level", type: "select", options: ["Entry", "Mid", "Senior", "Lead", "Manager", "Director"], required: true },
      { name: "keySkills", label: "Key Skills", type: "textarea", required: true },
      { name: "remote", label: "Work Location", type: "select", options: ["Remote", "Hybrid", "On-site"], required: true },
    ],
    systemPrompt: "You are a talent acquisition specialist. Write an engaging job description with: 1) Compelling intro, 2) Role overview, 3) Responsibilities, 4) Requirements, 5) Benefits, 6) Culture section. Use inclusive language.",
  },
  {
    slug: "email-subject-line-generator",
    name: "AI Email Subject Line Generator",
    shortDescription: "Generate high-converting email subject lines.",
    longDescription: "Create attention-grabbing subject lines optimized for open rates.",
    category: "Marketing",
    icon: "\ud83d\udce7",
    seoTitle: "Free AI Email Subject Line Generator | BizToolbox AI",
    seoDescription: "Generate high-converting email subject lines optimized for open rates.",
    seoKeywords: ["email subject line generator", "email marketing tool", "subject line optimizer"],
    fields: [
      { name: "emailType", label: "Email Type", type: "select", options: ["Newsletter", "Promotional", "Welcome", "Follow-up", "Cart Abandonment", "Announcement"], required: true },
      { name: "topic", label: "Email Content/Topic", type: "textarea", required: true },
      { name: "tone", label: "Tone", type: "select", options: ["Professional", "Casual", "Urgent", "Curious", "Friendly"], required: true },
    ],
    systemPrompt: "You are an email marketing expert. Generate 10 subject line variations under 50 characters that: 1) Create curiosity, 2) Use power words, 3) Avoid spam triggers, 4) Include emoji options. Rate each on predicted open rate 1-10.",
  },
  {
    slug: "refund-policy-generator",
    name: "AI Refund Policy Generator",
    shortDescription: "Create clear refund and return policies.",
    longDescription: "Generate professional refund policies covering timelines, conditions, and procedures.",
    category: "Legal",
    icon: "\ud83d\udcb0",
    seoTitle: "Free AI Refund Policy Generator | BizToolbox AI",
    seoDescription: "Create clear refund and return policies for your business.",
    seoKeywords: ["refund policy generator", "return policy template", "refund policy maker"],
    fields: [
      { name: "businessName", label: "Business Name", type: "text", required: true },
      { name: "businessType", label: "Type", type: "select", options: ["E-commerce", "SaaS", "Service", "Digital Products"], required: true },
      { name: "refundWindow", label: "Refund Window (days)", type: "number", placeholder: "30", required: true },
    ],
    systemPrompt: "You are a business policy specialist. Create a clear refund policy covering: 1) Eligibility, 2) Timeframe, 3) Process, 4) Exceptions, 5) Exchange options, 6) Contact info.",
  },
  {
    slug: "linkedin-post-generator",
    name: "AI LinkedIn Post Generator",
    shortDescription: "Create engaging LinkedIn posts that drive reach.",
    longDescription: "Generate professional LinkedIn content optimized for engagement and personal branding.",
    category: "Marketing",
    icon: "\ud83d\udcf1",
    seoTitle: "Free AI LinkedIn Post Generator | BizToolbox AI",
    seoDescription: "Create engaging LinkedIn posts that build your brand and drive engagement.",
    seoKeywords: ["LinkedIn post generator", "LinkedIn content writer", "social media post maker"],
    fields: [
      { name: "topic", label: "Post Topic", type: "text", required: true },
      { name: "postType", label: "Post Type", type: "select", options: ["Thought Leadership", "Story", "Tips/Advice", "Industry News", "Achievement", "Question"], required: true },
      { name: "keyMessage", label: "Key Message", type: "textarea", required: true },
    ],
    systemPrompt: "You are a LinkedIn content strategist. Create a post that: 1) Hooks with the first line, 2) Uses short paragraphs, 3) Tells a story or shares insights, 4) Ends with engagement prompt, 5) Includes hashtags.",
  },
  {
    slug: "expense-report-generator",
    name: "AI Expense Report Generator",
    shortDescription: "Create formatted expense reports quickly.",
    longDescription: "Generate professional expense reports with categories, totals, and approval sections.",
    category: "Finance",
    icon: "\ud83d\udcb3",
    seoTitle: "Free AI Expense Report Generator | BizToolbox AI",
    seoDescription: "Create professional expense reports instantly.",
    seoKeywords: ["expense report generator", "expense report template", "business expense tracker"],
    fields: [
      { name: "employeeName", label: "Employee Name", type: "text", required: true },
      { name: "department", label: "Department", type: "text", required: true },
      { name: "period", label: "Reporting Period", type: "text", required: true },
      { name: "expenses", label: "Expenses (date, description, amount)", type: "textarea", required: true },
    ],
    systemPrompt: "You are an accounting specialist. Create a formatted expense report with: 1) Employee info header, 2) Expense line items table, 3) Category subtotals, 4) Grand total, 5) Approval section.",
  },
    // Tools 21-35
  {
    slug: "press-release-generator",
    name: "AI Press Release Generator",
    shortDescription: "Write professional press releases in minutes.",
    longDescription: "Generate AP-style press releases for product launches, events, and company news.",
    category: "Marketing",
    icon: "\ud83d\udcf0",
    seoTitle: "Free AI Press Release Generator | BizToolbox AI",
    seoDescription: "Write professional press releases instantly. AP-style formatting for product launches and news.",
    seoKeywords: ["press release generator", "press release writer", "PR template"],
    fields: [
      { name: "headline", label: "Headline/News", type: "text", required: true },
      { name: "companyName", label: "Company Name", type: "text", required: true },
      { name: "details", label: "Key Details", type: "textarea", required: true },
      { name: "quote", label: "Executive Quote", type: "textarea", placeholder: "Optional quote from a company leader", required: false },
    ],
    systemPrompt: "You are a PR specialist. Write an AP-style press release with: 1) Compelling headline, 2) Dateline, 3) Strong opening paragraph (who, what, when, where, why), 4) Supporting details, 5) Executive quote, 6) Boilerplate, 7) Media contact info placeholder.",
  },
  {
    slug: "mission-statement-generator",
    name: "AI Mission Statement Generator",
    shortDescription: "Craft inspiring company mission statements.",
    longDescription: "Generate powerful mission statements that define your company purpose and values.",
    category: "Strategy",
    icon: "\ud83c\udf1f",
    seoTitle: "Free AI Mission Statement Generator | BizToolbox AI",
    seoDescription: "Craft inspiring company mission statements. Define your purpose and values.",
    seoKeywords: ["mission statement generator", "company mission writer", "vision statement maker"],
    fields: [
      { name: "companyName", label: "Company Name", type: "text", required: true },
      { name: "industry", label: "Industry", type: "text", required: true },
      { name: "values", label: "Core Values", type: "textarea", required: true },
      { name: "audience", label: "Who You Serve", type: "text", required: true },
    ],
    systemPrompt: "You are a brand strategist. Create 5 mission statement options that: 1) Are concise (1-2 sentences), 2) Define purpose, 3) Reflect values, 4) Inspire action, 5) Are memorable. Also create a vision statement and list of core values.",
  },
  {
    slug: "performance-review-generator",
    name: "AI Performance Review Generator",
    shortDescription: "Write balanced, constructive performance reviews.",
    longDescription: "Generate professional performance reviews with strengths, areas for improvement, and goals.",
    category: "HR",
    icon: "\ud83d\udcdd",
    seoTitle: "Free AI Performance Review Generator | BizToolbox AI",
    seoDescription: "Write balanced performance reviews with strengths, improvements, and goals.",
    seoKeywords: ["performance review generator", "employee review writer", "appraisal template"],
    fields: [
      { name: "employeeName", label: "Employee Name", type: "text", required: true },
      { name: "role", label: "Role/Position", type: "text", required: true },
      { name: "strengths", label: "Key Strengths", type: "textarea", required: true },
      { name: "improvements", label: "Areas for Improvement", type: "textarea", required: true },
      { name: "rating", label: "Overall Rating", type: "select", options: ["Exceeds Expectations", "Meets Expectations", "Needs Improvement"], required: true },
    ],
    systemPrompt: "You are an HR professional. Write a balanced performance review with: 1) Summary, 2) Key accomplishments, 3) Strengths with examples, 4) Constructive improvement areas, 5) SMART goals for next period, 6) Overall assessment. Use specific, actionable language.",
  },
  {
    slug: "sales-proposal-generator",
    name: "AI Sales Proposal Generator",
    shortDescription: "Create winning sales proposals quickly.",
    longDescription: "Generate professional sales proposals with problem statements, solutions, and pricing.",
    category: "Sales",
    icon: "\ud83d\udcc8",
    seoTitle: "Free AI Sales Proposal Generator | BizToolbox AI",
    seoDescription: "Create winning sales proposals with problem statements, solutions, and pricing sections.",
    seoKeywords: ["sales proposal generator", "business proposal writer", "proposal template"],
    fields: [
      { name: "companyName", label: "Your Company", type: "text", required: true },
      { name: "clientName", label: "Client/Prospect Name", type: "text", required: true },
      { name: "problem", label: "Client Problem", type: "textarea", required: true },
      { name: "solution", label: "Your Solution", type: "textarea", required: true },
      { name: "pricing", label: "Pricing/Budget", type: "text", required: false },
    ],
    systemPrompt: "You are a sales consultant. Create a compelling proposal with: 1) Executive summary, 2) Problem statement, 3) Proposed solution, 4) Scope and deliverables, 5) Timeline, 6) Pricing, 7) Why choose us, 8) Next steps.",
  },
  {
    slug: "sop-generator",
    name: "AI SOP Generator",
    shortDescription: "Create standard operating procedures for any process.",
    longDescription: "Generate detailed SOPs with step-by-step instructions and process documentation.",
    category: "HR",
    icon: "\ud83d\udcda",
    seoTitle: "Free AI SOP Generator | BizToolbox AI",
    seoDescription: "Create professional standard operating procedures for any business process.",
    seoKeywords: ["SOP generator", "standard operating procedure template", "process documentation"],
    fields: [
      { name: "processName", label: "Process Name", type: "text", required: true },
      { name: "department", label: "Department", type: "text", required: true },
      { name: "steps", label: "Key Steps/Overview", type: "textarea", required: true },
      { name: "audience", label: "Who Will Use This SOP", type: "text", required: true },
    ],
    systemPrompt: "You are a process documentation specialist. Create a detailed SOP with: 1) Purpose, 2) Scope, 3) Responsibilities, 4) Numbered step-by-step procedures, 5) Safety/compliance notes, 6) Troubleshooting tips, 7) Revision history section.",
  },
  {
    slug: "social-media-strategy-generator",
    name: "AI Social Media Strategy Generator",
    shortDescription: "Build comprehensive social media strategies.",
    longDescription: "Generate detailed social media plans with content calendars and platform strategies.",
    category: "Marketing",
    icon: "\ud83d\udcf2",
    seoTitle: "Free AI Social Media Strategy Generator | BizToolbox AI",
    seoDescription: "Build comprehensive social media strategies with content calendars and platform guides.",
    seoKeywords: ["social media strategy generator", "social media plan", "content strategy maker"],
    fields: [
      { name: "businessName", label: "Business Name", type: "text", required: true },
      { name: "industry", label: "Industry", type: "text", required: true },
      { name: "platforms", label: "Platforms", type: "textarea", placeholder: "Instagram, LinkedIn, TikTok, etc.", required: true },
      { name: "goals", label: "Goals", type: "select", options: ["Brand Awareness", "Lead Generation", "Sales", "Community Building", "Thought Leadership"], required: true },
    ],
    systemPrompt: "You are a social media strategist. Create a comprehensive strategy with: 1) Platform-specific tactics, 2) Content pillars, 3) Posting frequency, 4) Content mix, 5) Hashtag strategy, 6) Engagement tactics, 7) One-week content calendar example.",
  },
  {
    slug: "competitive-analysis-generator",
    name: "AI Competitive Analysis Generator",
    shortDescription: "Analyze competitors and find your advantages.",
    longDescription: "Generate detailed competitive analyses comparing features, pricing, and positioning.",
    category: "Strategy",
    icon: "\ud83d\udd0d",
    seoTitle: "Free AI Competitive Analysis Generator | BizToolbox AI",
    seoDescription: "Analyze competitors and find your competitive advantages.",
    seoKeywords: ["competitive analysis generator", "competitor analysis tool", "market analysis"],
    fields: [
      { name: "yourBusiness", label: "Your Business", type: "text", required: true },
      { name: "competitors", label: "Competitors (2-4)", type: "textarea", placeholder: "List competitor names and URLs", required: true },
      { name: "industry", label: "Industry", type: "text", required: true },
    ],
    systemPrompt: "You are a business analyst. Create a competitive analysis with: 1) Competitor profiles, 2) Feature comparison table, 3) Pricing comparison, 4) SWOT for each, 5) Market positioning map description, 6) Your competitive advantages, 7) Strategic recommendations.",
  },
  {
    slug: "testimonial-request-email",
    name: "AI Testimonial Request Email Writer",
    shortDescription: "Write emails that actually get testimonials.",
    longDescription: "Generate persuasive testimonial request emails for clients and customers.",
    category: "Sales",
    icon: "\u2b50",
    seoTitle: "Free AI Testimonial Request Email Writer | BizToolbox AI",
    seoDescription: "Write emails that get testimonials from clients.",
    seoKeywords: ["testimonial request email", "review request template", "client testimonial"],
    fields: [
      { name: "clientName", label: "Client Name", type: "text", required: true },
      { name: "service", label: "Service/Product Provided", type: "text", required: true },
      { name: "result", label: "Results Achieved", type: "textarea", required: true },
    ],
    systemPrompt: "You are a customer success manager. Write a warm, non-pushy testimonial request email that: 1) Thanks the client, 2) References specific results, 3) Makes it easy with guiding questions, 4) Offers multiple format options (written, video, LinkedIn), 5) Shows appreciation.",
  },
  {
    slug: "project-scope-generator",
    name: "AI Project Scope Generator",
    shortDescription: "Define project scopes with clear deliverables.",
    longDescription: "Generate detailed project scope documents with objectives, deliverables, and timelines.",
    category: "Strategy",
    icon: "\ud83d\udccb",
    seoTitle: "Free AI Project Scope Generator | BizToolbox AI",
    seoDescription: "Define project scopes with clear deliverables and timelines.",
    seoKeywords: ["project scope generator", "scope document template", "project planning tool"],
    fields: [
      { name: "projectName", label: "Project Name", type: "text", required: true },
      { name: "objective", label: "Project Objective", type: "textarea", required: true },
      { name: "stakeholders", label: "Key Stakeholders", type: "text", required: true },
      { name: "timeline", label: "Expected Timeline", type: "text", required: true },
      { name: "budget", label: "Budget Range", type: "text", required: false },
    ],
    systemPrompt: "You are a project manager. Create a project scope document with: 1) Executive summary, 2) Objectives, 3) Deliverables, 4) In-scope and out-of-scope items, 5) Timeline with milestones, 6) Resources needed, 7) Risks and assumptions, 8) Acceptance criteria.",
  },
  {
    slug: "newsletter-generator",
    name: "AI Newsletter Generator",
    shortDescription: "Create engaging email newsletters quickly.",
    longDescription: "Generate professional newsletter content with sections, CTAs, and engaging copy.",
    category: "Marketing",
    icon: "\ud83d\udce8",
    seoTitle: "Free AI Newsletter Generator | BizToolbox AI",
    seoDescription: "Create engaging email newsletters with professional formatting.",
    seoKeywords: ["newsletter generator", "email newsletter writer", "newsletter template"],
    fields: [
      { name: "companyName", label: "Company/Brand Name", type: "text", required: true },
      { name: "topics", label: "This Week's Topics", type: "textarea", required: true },
      { name: "tone", label: "Tone", type: "select", options: ["Professional", "Casual", "Educational", "Fun"], required: true },
      { name: "cta", label: "Main CTA", type: "text", placeholder: "What should readers do?", required: true },
    ],
    systemPrompt: "You are an email marketing specialist. Create a newsletter with: 1) Catchy subject line, 2) Preview text, 3) Opening hook, 4) 3-4 content sections, 5) Tips or value-add, 6) Clear CTA, 7) Footer with social links placeholder. Use scannable formatting.",
  },
  {
    slug: "business-name-generator",
    name: "AI Business Name Generator",
    shortDescription: "Generate creative, available business names.",
    longDescription: "Create unique business name ideas with domain availability considerations.",
    category: "Strategy",
    icon: "\ud83d\udca1",
    seoTitle: "Free AI Business Name Generator | BizToolbox AI",
    seoDescription: "Generate creative business names with domain considerations.",
    seoKeywords: ["business name generator", "company name ideas", "brand name maker"],
    fields: [
      { name: "industry", label: "Industry", type: "text", required: true },
      { name: "keywords", label: "Keywords/Themes", type: "textarea", required: true },
      { name: "style", label: "Name Style", type: "select", options: ["Modern/Tech", "Classic/Traditional", "Fun/Creative", "Professional", "Minimalist"], required: true },
    ],
    systemPrompt: "You are a branding expert. Generate 20 business name ideas that: 1) Are memorable and easy to spell, 2) Suggest .com domain availability, 3) Include meaning/rationale, 4) Mix different naming strategies (descriptive, abstract, compound, acronym), 5) Consider trademark searchability.",
  },
  {
    slug: "follow-up-email-writer",
    name: "AI Follow-Up Email Writer",
    shortDescription: "Write effective follow-up emails that get responses.",
    longDescription: "Generate professional follow-up emails for sales, networking, and business situations.",
    category: "Communication",
    icon: "\ud83d\udce9",
    seoTitle: "Free AI Follow-Up Email Writer | BizToolbox AI",
    seoDescription: "Write effective follow-up emails that get responses.",
    seoKeywords: ["follow-up email generator", "follow up email template", "professional follow-up"],
    fields: [
      { name: "context", label: "Original Interaction", type: "select", options: ["Sales Meeting", "Job Interview", "Networking Event", "Proposal Sent", "No Response", "After Purchase"], required: true },
      { name: "recipientName", label: "Recipient Name", type: "text", required: true },
      { name: "details", label: "Key Details", type: "textarea", required: true },
      { name: "daysElapsed", label: "Days Since Last Contact", type: "number", placeholder: "3", required: true },
    ],
    systemPrompt: "You are a communication expert. Write a follow-up email that: 1) References the previous interaction, 2) Adds new value, 3) Has a clear ask, 4) Is concise, 5) Isn't pushy. Adjust tone based on days elapsed and context.",
  },
  {
    slug: "contract-template-generator",
    name: "AI Contract Template Generator",
    shortDescription: "Generate basic business contract templates.",
    longDescription: "Create customizable contract templates for freelancers, services, and partnerships.",
    category: "Legal",
    icon: "\ud83d\udcdc",
    seoTitle: "Free AI Contract Template Generator | BizToolbox AI",
    seoDescription: "Generate basic business contract templates for services and partnerships.",
    seoKeywords: ["contract template generator", "business contract maker", "freelance contract"],
    fields: [
      { name: "contractType", label: "Contract Type", type: "select", options: ["Service Agreement", "Freelance Contract", "NDA", "Partnership Agreement", "Consulting Agreement"], required: true },
      { name: "partyA", label: "Party A (Your Business)", type: "text", required: true },
      { name: "partyB", label: "Party B (Other Party)", type: "text", required: true },
      { name: "scope", label: "Scope of Work/Agreement", type: "textarea", required: true },
    ],
    systemPrompt: "You are a legal document specialist. Generate a contract template with: 1) Parties involved, 2) Scope/services, 3) Payment terms, 4) Duration, 5) Termination clauses, 6) Confidentiality, 7) Liability, 8) Signatures section. Note: This is a template and should be reviewed by a lawyer.",
  },
  {
    slug: "customer-survey-generator",
    name: "AI Customer Survey Generator",
    shortDescription: "Create effective customer feedback surveys.",
    longDescription: "Generate well-structured surveys with mix of question types for actionable feedback.",
    category: "Sales",
    icon: "\ud83d\udcca",
    seoTitle: "Free AI Customer Survey Generator | BizToolbox AI",
    seoDescription: "Create effective customer feedback surveys with diverse question types.",
    seoKeywords: ["customer survey generator", "feedback survey template", "satisfaction survey maker"],
    fields: [
      { name: "surveyGoal", label: "Survey Goal", type: "select", options: ["Customer Satisfaction", "Product Feedback", "NPS Score", "Market Research", "Churn Prevention"], required: true },
      { name: "product", label: "Product/Service", type: "text", required: true },
      { name: "questionCount", label: "Number of Questions", type: "select", options: ["5-8", "10-15", "15-20"], required: true },
    ],
    systemPrompt: "You are a market researcher. Create a survey with: 1) Clear intro, 2) Mix of question types (multiple choice, Likert scale, open-ended), 3) Logical flow, 4) No leading questions, 5) Thank you message. Include scoring methodology.",
  },
  {
    slug: "brand-voice-guide-generator",
    name: "AI Brand Voice Guide Generator",
    shortDescription: "Define your brand voice and tone guidelines.",
    longDescription: "Generate comprehensive brand voice guides with dos, don'ts, and examples.",
    category: "Marketing",
    icon: "\ud83c\udfa8",
    seoTitle: "Free AI Brand Voice Guide Generator | BizToolbox AI",
    seoDescription: "Define your brand voice and tone with comprehensive guidelines.",
    seoKeywords: ["brand voice guide", "tone of voice generator", "brand guidelines maker"],
    fields: [
      { name: "brandName", label: "Brand Name", type: "text", required: true },
      { name: "industry", label: "Industry", type: "text", required: true },
      { name: "personality", label: "Brand Personality Traits", type: "textarea", placeholder: "e.g., friendly, professional, innovative", required: true },
      { name: "audience", label: "Target Audience", type: "text", required: true },
    ],
    systemPrompt: "You are a brand strategist. Create a brand voice guide with: 1) Voice attributes, 2) Tone variations by context, 3) Do's and don'ts, 4) Word choice guidelines, 5) Example copy for different channels, 6) Writing style rules.",
  },
    // Tools 36-50
  {
    slug: "employee-handbook-generator",
    name: "AI Employee Handbook Generator",
    shortDescription: "Create comprehensive employee handbooks.",
    longDescription: "Generate professional employee handbooks covering policies, benefits, and workplace guidelines.",
    category: "HR",
    icon: "\ud83d\udcd6",
    seoTitle: "Free AI Employee Handbook Generator | BizToolbox AI",
    seoDescription: "Create comprehensive employee handbooks with policies and guidelines.",
    seoKeywords: ["employee handbook generator", "company policy handbook", "HR handbook template"],
    fields: [
      { name: "companyName", label: "Company Name", type: "text", required: true },
      { name: "industry", label: "Industry", type: "text", required: true },
      { name: "companySize", label: "Company Size", type: "select", options: ["1-10", "11-50", "51-200", "200+"], required: true },
      { name: "topics", label: "Key Topics to Cover", type: "textarea", required: true },
    ],
    systemPrompt: "You are an HR consultant. Create an employee handbook section covering: 1) Welcome message, 2) Company overview, 3) Employment policies, 4) Code of conduct, 5) Benefits overview, 6) Leave policies, 7) Communication guidelines.",
  },
  {
    slug: "landing-page-copy-generator",
    name: "AI Landing Page Copy Generator",
    shortDescription: "Write high-converting landing page copy.",
    longDescription: "Generate persuasive landing page copy with headlines, benefits, and CTAs.",
    category: "Marketing",
    icon: "\ud83d\udcbb",
    seoTitle: "Free AI Landing Page Copy Generator | BizToolbox AI",
    seoDescription: "Write high-converting landing page copy with headlines, benefits, and CTAs.",
    seoKeywords: ["landing page copy generator", "landing page writer", "conversion copy maker"],
    fields: [
      { name: "product", label: "Product/Service", type: "text", required: true },
      { name: "targetAudience", label: "Target Audience", type: "text", required: true },
      { name: "mainBenefit", label: "Main Benefit", type: "text", required: true },
      { name: "features", label: "Key Features (3-5)", type: "textarea", required: true },
      { name: "style", label: "Style", type: "select", options: ["SaaS", "E-commerce", "Service", "App", "Course"], required: true },
    ],
    systemPrompt: "You are a conversion copywriter. Write landing page copy with: 1) Attention-grabbing headline, 2) Sub-headline, 3) Hero section copy, 4) Benefits section, 5) Social proof section, 6) FAQ section, 7) Final CTA. Optimize for conversion.",
  },
  {
    slug: "pitch-deck-outline-generator",
    name: "AI Pitch Deck Outline Generator",
    shortDescription: "Create investor-ready pitch deck outlines.",
    longDescription: "Generate structured pitch deck outlines with talking points for each slide.",
    category: "Sales",
    icon: "\ud83d\udcca",
    seoTitle: "Free AI Pitch Deck Outline Generator | BizToolbox AI",
    seoDescription: "Create investor-ready pitch deck outlines with talking points.",
    seoKeywords: ["pitch deck generator", "investor pitch template", "startup pitch maker"],
    fields: [
      { name: "companyName", label: "Company Name", type: "text", required: true },
      { name: "problem", label: "Problem", type: "textarea", required: true },
      { name: "solution", label: "Solution", type: "textarea", required: true },
      { name: "stage", label: "Stage", type: "select", options: ["Pre-seed", "Seed", "Series A", "Series B+"], required: true },
      { name: "askAmount", label: "Funding Ask", type: "text", required: false },
    ],
    systemPrompt: "You are a startup advisor. Create a pitch deck outline with slides: 1) Title, 2) Problem, 3) Solution, 4) Market size, 5) Business model, 6) Traction, 7) Team, 8) Competition, 9) Financials, 10) The Ask. Include talking points per slide.",
  },
  {
    slug: "apology-email-writer",
    name: "AI Apology Email Writer",
    shortDescription: "Write professional apology emails that rebuild trust.",
    longDescription: "Generate sincere business apology emails for service issues, delays, and mistakes.",
    category: "Communication",
    icon: "\ud83d\ude4f",
    seoTitle: "Free AI Apology Email Writer | BizToolbox AI",
    seoDescription: "Write professional apology emails that rebuild customer trust.",
    seoKeywords: ["apology email generator", "business apology template", "sorry email writer"],
    fields: [
      { name: "situation", label: "What Happened", type: "textarea", required: true },
      { name: "recipientType", label: "Recipient", type: "select", options: ["Customer", "Client", "Partner", "Team/Employee", "Public/Mass"], required: true },
      { name: "resolution", label: "Resolution/Fix", type: "textarea", required: true },
    ],
    systemPrompt: "You are a crisis communication expert. Write an apology email that: 1) Acknowledges the issue directly, 2) Takes responsibility, 3) Explains what happened (briefly), 4) Details the fix, 5) Offers compensation if appropriate, 6) Prevents recurrence.",
  },
  {
    slug: "roi-calculator-content",
    name: "AI ROI Calculator Content Generator",
    shortDescription: "Create ROI calculators and value propositions.",
    longDescription: "Generate ROI analysis frameworks and value propositions for your product.",
    category: "Sales",
    icon: "\ud83d\udcb5",
    seoTitle: "Free AI ROI Calculator Content Generator | BizToolbox AI",
    seoDescription: "Create ROI analysis content and value propositions.",
    seoKeywords: ["ROI calculator generator", "value proposition tool", "ROI analysis maker"],
    fields: [
      { name: "product", label: "Product/Service", type: "text", required: true },
      { name: "targetCustomer", label: "Target Customer", type: "text", required: true },
      { name: "pricing", label: "Your Pricing", type: "text", required: true },
      { name: "benefits", label: "Key Benefits/Savings", type: "textarea", required: true },
    ],
    systemPrompt: "You are a sales enablement specialist. Create ROI analysis content with: 1) Value proposition summary, 2) Cost-benefit breakdown, 3) ROI calculation framework, 4) Payback period estimate, 5) Comparison scenarios, 6) Key metrics to track.",
  },
  {
    slug: "faq-generator",
    name: "AI FAQ Generator",
    shortDescription: "Generate comprehensive FAQ sections for any business.",
    longDescription: "Create well-organized FAQ pages covering common customer questions.",
    category: "Marketing",
    icon: "\u2753",
    seoTitle: "Free AI FAQ Generator | BizToolbox AI",
    seoDescription: "Generate comprehensive FAQ sections for your website or product.",
    seoKeywords: ["FAQ generator", "FAQ page creator", "frequently asked questions maker"],
    fields: [
      { name: "businessName", label: "Business Name", type: "text", required: true },
      { name: "product", label: "Product/Service", type: "text", required: true },
      { name: "topics", label: "Topics to Cover", type: "textarea", placeholder: "Pricing, shipping, returns, etc.", required: true },
      { name: "count", label: "Number of FAQs", type: "select", options: ["10", "15", "20", "25"], required: true },
    ],
    systemPrompt: "You are a customer experience specialist. Generate FAQs that: 1) Address real customer concerns, 2) Are grouped by category, 3) Use conversational language, 4) Are SEO-friendly, 5) Include schema markup suggestions.",
  },
  {
    slug: "startup-cost-estimator",
    name: "AI Startup Cost Estimator",
    shortDescription: "Estimate startup costs for your business idea.",
    longDescription: "Generate detailed startup cost breakdowns with one-time and recurring expenses.",
    category: "Finance",
    icon: "\ud83d\udcb0",
    seoTitle: "Free AI Startup Cost Estimator | BizToolbox AI",
    seoDescription: "Estimate startup costs with detailed expense breakdowns.",
    seoKeywords: ["startup cost estimator", "business cost calculator", "startup budget planner"],
    fields: [
      { name: "businessType", label: "Business Type", type: "text", required: true },
      { name: "industry", label: "Industry", type: "text", required: true },
      { name: "location", label: "Location Type", type: "select", options: ["Online Only", "Physical Location", "Hybrid", "Home-based"], required: true },
      { name: "scale", label: "Initial Scale", type: "select", options: ["Solo/Freelance", "Small Team (2-5)", "Medium (6-20)", "Large (20+)"], required: true },
    ],
    systemPrompt: "You are a financial advisor for startups. Create a cost estimate with: 1) One-time startup costs, 2) Monthly recurring costs, 3) First-year budget projection, 4) Cost-saving tips, 5) Funding options, 6) Break-even estimate.",
  },
  {
    slug: "onboarding-checklist-generator",
    name: "AI Employee Onboarding Checklist Generator",
    shortDescription: "Create comprehensive onboarding checklists.",
    longDescription: "Generate structured onboarding plans for new employees with day-by-day activities.",
    category: "HR",
    icon: "\u2705",
    seoTitle: "Free AI Employee Onboarding Checklist | BizToolbox AI",
    seoDescription: "Create comprehensive employee onboarding checklists and plans.",
    seoKeywords: ["onboarding checklist generator", "new employee onboarding", "onboarding plan template"],
    fields: [
      { name: "role", label: "Role/Position", type: "text", required: true },
      { name: "department", label: "Department", type: "text", required: true },
      { name: "duration", label: "Onboarding Duration", type: "select", options: ["1 Week", "2 Weeks", "30 Days", "60 Days", "90 Days"], required: true },
      { name: "remote", label: "Work Setup", type: "select", options: ["Remote", "Hybrid", "In-office"], required: true },
    ],
    systemPrompt: "You are an HR onboarding specialist. Create an onboarding checklist with: 1) Pre-arrival tasks, 2) Day 1 activities, 3) Week 1 goals, 4) 30-60-90 day milestones, 5) Key meetings to schedule, 6) Training resources, 7) Success metrics.",
  },
  {
    slug: "cancellation-email-response",
    name: "AI Cancellation Response Email Writer",
    shortDescription: "Write retention-focused cancellation responses.",
    longDescription: "Generate professional cancellation response emails that retain customers.",
    category: "Sales",
    icon: "\ud83d\udce7",
    seoTitle: "Free AI Cancellation Response Email Writer | BizToolbox AI",
    seoDescription: "Write retention-focused cancellation response emails.",
    seoKeywords: ["cancellation email response", "customer retention email", "save customer template"],
    fields: [
      { name: "customerName", label: "Customer Name", type: "text", required: true },
      { name: "product", label: "Product/Service", type: "text", required: true },
      { name: "reason", label: "Cancellation Reason", type: "select", options: ["Too Expensive", "Not Using It", "Missing Features", "Poor Experience", "Switching Competitor", "Unknown"], required: true },
    ],
    systemPrompt: "You are a customer retention specialist. Write a response that: 1) Acknowledges their decision respectfully, 2) Addresses their specific concern, 3) Offers a relevant save offer, 4) Highlights unused value, 5) Makes it easy to stay or return later.",
  },
  {
    slug: "value-proposition-generator",
    name: "AI Value Proposition Generator",
    shortDescription: "Craft compelling value propositions.",
    longDescription: "Generate clear value propositions that differentiate your business.",
    category: "Strategy",
    icon: "\ud83d\udca1",
    seoTitle: "Free AI Value Proposition Generator | BizToolbox AI",
    seoDescription: "Craft compelling value propositions for your business.",
    seoKeywords: ["value proposition generator", "UVP maker", "value prop writer"],
    fields: [
      { name: "product", label: "Product/Service", type: "text", required: true },
      { name: "targetAudience", label: "Target Audience", type: "text", required: true },
      { name: "problem", label: "Problem You Solve", type: "textarea", required: true },
      { name: "competitors", label: "How You're Different", type: "textarea", required: true },
    ],
    systemPrompt: "You are a positioning expert. Create 5 value proposition variations using frameworks: 1) Steve Blank format, 2) Geoff Moore format, 3) Jobs-to-be-done, 4) Before/After/Bridge, 5) Problem-Agitate-Solve.",
  },
  {
    slug: "ad-copy-generator",
    name: "AI Ad Copy Generator",
    shortDescription: "Write high-performing ad copy for any platform.",
    longDescription: "Generate ad copy optimized for Google Ads, Facebook, Instagram, and more.",
    category: "Marketing",
    icon: "\ud83d\udce3",
    seoTitle: "Free AI Ad Copy Generator | BizToolbox AI",
    seoDescription: "Write high-performing ad copy for Google, Facebook, Instagram, and more.",
    seoKeywords: ["ad copy generator", "Google Ads writer", "Facebook ad copy maker"],
    fields: [
      { name: "platform", label: "Ad Platform", type: "select", options: ["Google Ads", "Facebook/Instagram", "LinkedIn", "Twitter/X", "TikTok"], required: true },
      { name: "product", label: "Product/Service", type: "text", required: true },
      { name: "audience", label: "Target Audience", type: "text", required: true },
      { name: "goal", label: "Campaign Goal", type: "select", options: ["Awareness", "Traffic", "Leads", "Sales", "App Installs"], required: true },
      { name: "budget", label: "Budget Level", type: "select", options: ["Low (<$500/mo)", "Medium ($500-2k/mo)", "High ($2k+/mo)"], required: false },
    ],
    systemPrompt: "You are a performance marketing expert. Generate 5 ad variations for the specified platform with: 1) Headlines, 2) Body copy, 3) CTAs, 4) Character count compliance, 5) A/B test suggestions. Follow platform-specific best practices.",
  },
  {
    slug: "cash-flow-projection-generator",
    name: "AI Cash Flow Projection Generator",
    shortDescription: "Create cash flow projections for your business.",
    longDescription: "Generate monthly cash flow forecasts with income, expenses, and runway calculations.",
    category: "Finance",
    icon: "\ud83d\udcb8",
    seoTitle: "Free AI Cash Flow Projection Generator | BizToolbox AI",
    seoDescription: "Create cash flow projections and financial forecasts for your business.",
    seoKeywords: ["cash flow projection generator", "financial forecast tool", "cash flow template"],
    fields: [
      { name: "businessType", label: "Business Type", type: "text", required: true },
      { name: "monthlyRevenue", label: "Current Monthly Revenue", type: "text", required: true },
      { name: "monthlyExpenses", label: "Monthly Expenses (approx)", type: "text", required: true },
      { name: "projectionPeriod", label: "Projection Period", type: "select", options: ["3 Months", "6 Months", "12 Months"], required: true },
      { name: "growthRate", label: "Expected Monthly Growth %", type: "text", placeholder: "10", required: false },
    ],
    systemPrompt: "You are a financial analyst. Create a cash flow projection with: 1) Monthly income breakdown, 2) Expense categories, 3) Net cash flow per month, 4) Cumulative cash position, 5) Runway calculation, 6) Scenarios (best/worst/likely), 7) Key assumptions.",
  },
  {
    slug: "partnership-proposal-generator",
    name: "AI Partnership Proposal Generator",
    shortDescription: "Write compelling partnership proposals.",
    longDescription: "Generate professional partnership proposals highlighting mutual benefits.",
    category: "Sales",
    icon: "\ud83e\udd1d",
    seoTitle: "Free AI Partnership Proposal Generator | BizToolbox AI",
    seoDescription: "Write compelling partnership proposals highlighting mutual benefits.",
    seoKeywords: ["partnership proposal generator", "business partnership template", "collaboration proposal"],
    fields: [
      { name: "yourBusiness", label: "Your Business", type: "text", required: true },
      { name: "partnerBusiness", label: "Potential Partner", type: "text", required: true },
      { name: "partnershipType", label: "Partnership Type", type: "select", options: ["Co-marketing", "Referral", "Integration", "White Label", "Joint Venture", "Affiliate"], required: true },
      { name: "mutualBenefits", label: "Mutual Benefits", type: "textarea", required: true },
    ],
    systemPrompt: "You are a business development expert. Create a partnership proposal with: 1) Introduction, 2) Why this partnership, 3) Mutual benefits, 4) Proposed structure, 5) Revenue/value sharing, 6) Timeline, 7) Success metrics, 8) Next steps.",
  },
  {
    slug: "company-bio-generator",
    name: "AI Company Bio Generator",
    shortDescription: "Write professional company bios and about pages.",
    longDescription: "Generate compelling company bios for websites, social profiles, and directories.",
    category: "Marketing",
    icon: "\ud83c\udfe2",
    seoTitle: "Free AI Company Bio Generator | BizToolbox AI",
    seoDescription: "Write professional company bios for websites and directories.",
    seoKeywords: ["company bio generator", "about us writer", "company description maker"],
    fields: [
      { name: "companyName", label: "Company Name", type: "text", required: true },
      { name: "industry", label: "Industry", type: "text", required: true },
      { name: "founded", label: "Year Founded", type: "text", required: false },
      { name: "mission", label: "Mission/What You Do", type: "textarea", required: true },
      { name: "length", label: "Bio Length", type: "select", options: ["Short (50 words)", "Medium (150 words)", "Long (300+ words)"], required: true },
    ],
    systemPrompt: "You are a brand copywriter. Generate company bios in 3 lengths that: 1) Lead with what you do, 2) Highlight achievements, 3) Show personality, 4) Include a clear value proposition, 5) Are optimized for the platform.",
  },
  {
    slug: "weekly-report-generator",
    name: "AI Weekly Report Generator",
    shortDescription: "Generate professional weekly status reports.",
    longDescription: "Create structured weekly reports with accomplishments, metrics, and next steps.",
    category: "Communication",
    icon: "\ud83d\udcca",
    seoTitle: "Free AI Weekly Report Generator | BizToolbox AI",
    seoDescription: "Generate professional weekly status reports instantly.",
    seoKeywords: ["weekly report generator", "status report template", "progress report maker"],
    fields: [
      { name: "name", label: "Your Name/Team", type: "text", required: true },
      { name: "accomplishments", label: "This Week's Accomplishments", type: "textarea", required: true },
      { name: "challenges", label: "Challenges/Blockers", type: "textarea", required: false },
      { name: "nextWeek", label: "Next Week's Priorities", type: "textarea", required: true },
      { name: "metrics", label: "Key Metrics/Numbers", type: "textarea", placeholder: "Sales, signups, etc.", required: false },
    ],
    systemPrompt: "You are a project manager. Create a concise weekly report with: 1) Executive summary, 2) Accomplishments with impact, 3) Metrics dashboard, 4) Challenges and mitigation, 5) Next week priorities, 6) Help needed section.",
  },
];

export function getToolBySlug(slug: string): ToolConfig | undefined {
  return tools.find((t) => t.slug === slug);
}

export function getToolsByCategory(category: string): ToolConfig[] {
  return tools.filter((t) => t.category === category);
}

export function getAllCategories(): string[] {
  return [...new Set(tools.map((t) => t.category))];
}