import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Pricing - BizToolbox AI",
    description: "Simple pricing for AI business tools. Free, Starter $7/mo, Pro $19/mo. No hidden fees.",
    };

    const check = "\u2713";

    const tiers = [
      {
          name: "Free", price: "$0", period: "/forever",
              desc: "Perfect for trying out our tools.",
                  cta: "Start Free", link: "/tools", pop: false,
                      features: ["3 uses per day", "All 50 tools", "No signup required", "Copy results", "Standard AI model"],
                        },
                          {
                              name: "Starter", price: "$7", period: "/month",
                                  desc: "For regular users who want more.",
                                      cta: "Get Starter", link: "/signin", pop: false,
                                          features: ["20 uses per day", "All 50 tools", "Save history (20 projects)", "Brand voice profile", "Standard AI model", "Export as text"],
                                            },
                                              {
                                                  name: "Pro", price: "$19", period: "/month",
                                                      desc: "Unlimited power for serious businesses.",
                                                          cta: "Go Pro", link: "/signin", pop: true,
                                                              features: ["Unlimited uses", "All 50 tools", "Unlimited saved projects", "Brand voice profile", "GPT-4o premium model", "Export PDF & Word", "Priority support", "3 output variations", "File upload & analysis"],
                                                                },
                                                                ];

                                                                const testimonials = [
                                                                  { name: "Sarah M.", role: "Founder, Bloom Digital", text: "BizToolbox saved me hours every week. The cold email writer alone has booked me 12 new client calls.", rating: 5 },
                                                                    { name: "James K.", role: "Marketing Lead, ScaleUp", text: "I replaced three separate AI tools with this one platform. The business plan generator is incredibly detailed.", rating: 5 },
                                                                    ];

                                                                    export default function PricingPage() {
                                                                      return (
                                                                          <div className="max-w-6xl mx-auto px-4 py-16">
                                                                                <div className="text-center mb-4">
                                                                                        <div className="inline-block bg-blue-100 text-blue-700 text-sm font-medium px-4 py-1 rounded-full mb-4">Trusted by 2,000+ businesses</div>
                                                                                                <h1 className="text-4xl font-bold text-gray-900 mb-4">Simple, Transparent Pricing</h1>
                                                                                                        <p className="text-xl text-gray-600">Start free. Upgrade when you need more power.</p>
                                                                                                              </div>

                                                                                                                    <div className="flex justify-center gap-1 mb-12">{[1,2,3,4,5].map(i => <span key={i} className="text-yellow-400 text-xl">&#9733;</span>)}<span className="text-sm text-gray-500 ml-2 self-center">4.9/5 from 200+ reviews</span></div>

                                                                                                                          <div className="grid md:grid-cols-3 gap-8 max-w-5xl mx-auto">
                                                                                                                                  {tiers.map((tier) => (
                                                                                                                                            <div key={tier.name} className={"border-2 rounded-2xl p-8 relative " + (tier.pop ? "border-blue-600 shadow-lg" : "border-gray-200")}>
                                                                                                                                                        {tier.pop && <div className="absolute -top-3 left-1/2 transform -translate-x-1/2 bg-blue-600 text-white px-4 py-1 rounded-full text-sm font-medium">Most Popular</div>}
                                                                                                                                                                    <h2 className="text-2xl font-bold text-gray-900 mb-1">{tier.name}</h2>
                                                                                                                                                                                <p className="text-gray-500 text-sm mb-4">{tier.desc}</p>
                                                                                                                                                                                            <div className="mb-6"><span className="text-4xl font-bold">{tier.price}</span><span className="text-gray-500">{tier.period}</span></div>
                                                                                                                                                                                                        <ul className="space-y-3 mb-8">{tier.features.map((f) => (<li key={f} className="flex items-start gap-2 text-gray-600 text-sm"><span className="text-green-500 mt-0.5">{check}</span>{f}</li>))}</ul>
                                                                                                                                                                                                                    <Link href={tier.link} className={"block w-full text-center py-3 px-6 rounded-lg font-medium transition " + (tier.pop ? "bg-blue-600 text-white hover:bg-blue-700" : "border-2 border-blue-600 text-blue-600 hover:bg-blue-50")}>{tier.cta}</Link>
                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                      ))}
                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                  {/* Social Proof on Pricing */}
                                                                                                                                                                                                                                                        <div className="mt-16 max-w-4xl mx-auto">
                                                                                                                                                                                                                                                                <h3 className="text-2xl font-bold text-center text-gray-900 mb-8">What Our Users Say</h3>
                                                                                                                                                                                                                                                                        <div className="grid md:grid-cols-2 gap-6">
                                                                                                                                                                                                                                                                                  {testimonials.map((t) => (
                                                                                                                                                                                                                                                                                              <div key={t.name} className="bg-gray-50 rounded-xl p-6 border">
                                                                                                                                                                                                                                                                                                            <div className="flex mb-2">{Array.from({length: t.rating}).map((_, i) => <span key={i} className="text-yellow-400">&#9733;</span>)}</div>
                                                                                                                                                                                                                                                                                                                          <p className="text-gray-700 mb-3 text-sm">{t.text}</p>
                                                                                                                                                                                                                                                                                                                                        <p className="font-semibold text-gray-900 text-sm">{t.name}</p>
                                                                                                                                                                                                                                                                                                                                                      <p className="text-gray-500 text-xs">{t.role}</p>
                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                            ))}
                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                {/* FAQ */}
                                                                                                                                                                                                                                                                                                                                                                                                      <div className="mt-16 max-w-3xl mx-auto">
                                                                                                                                                                                                                                                                                                                                                                                                              <h3 className="text-2xl font-bold text-center text-gray-900 mb-8">Frequently Asked Questions</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="space-y-6">
                                                                                                                                                                                                                                                                                                                                                                                                                                <div><h4 className="font-medium text-gray-900">Do I need to sign up?</h4><p className="text-gray-600 mt-1 text-sm">No! Free users can use any tool without an account. Sign up to save work and access history.</p></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                          <div><h4 className="font-medium text-gray-900">What counts as a use?</h4><p className="text-gray-600 mt-1 text-sm">Each Generate click counts as one use. Free gets 3/day, Starter 20/day, Pro unlimited.</p></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div><h4 className="font-medium text-gray-900">What is Brand Voice?</h4><p className="text-gray-600 mt-1 text-sm">Save your company details so every generation is personalized to your brand automatically.</p></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div><h4 className="font-medium text-gray-900">Can I cancel anytime?</h4><p className="text-gray-600 mt-1 text-sm">Yes. Cancel anytime, keep access until the end of your billing period.</p></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div><h4 className="font-medium text-gray-900">GPT-4o vs Standard?</h4><p className="text-gray-600 mt-1 text-sm">Pro uses GPT-4o for longer, more nuanced outputs. Free and Starter use GPT-4o-mini.</p></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {/* Bottom CTA */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="mt-16 bg-gray-50 rounded-2xl p-8 text-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <h3 className="text-xl font-bold text-gray-900 mb-2">Still not sure?</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p className="text-gray-600 mb-4">Try any tool free. No signup, no credit card.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Link href="/tools" className="inline-block bg-blue-600 text-white px-8 py-3 rounded-lg font-medium hover:bg-blue-700 transition">Browse All 50 Tools</Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }