import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Pricing - BizToolbox AI",
    description: "Simple, transparent pricing. Get 3 free uses per day or upgrade to Pro for unlimited access to all 50 AI business tools.",
    };

    export default function PricingPage() {
      return (
          <div className="max-w-5xl mx-auto px-4 py-16">
                <div className="text-center mb-12">
                        <h1 className="text-4xl font-bold text-gray-900 mb-4">
                                  Simple, Transparent Pricing
                                          </h1>
                                                  <p className="text-xl text-gray-600">
                                                              Start free. Upgrade when you need more.
                                                                      </p>
                                                                            </div>

                                                                                  <div className="grid md:grid-cols-2 gap-8 max-w-3xl mx-auto">
                                                                                          {/* Free Tier */}
                                                                                                  <div className="border-2 border-gray-200 rounded-2xl p-8">
                                                                                                            <h2 className="text-2xl font-bold text-gray-900 mb-2">Free</h2>
                                                                                                                      <div className="mb-4">
                                                                                                                                  <span className="text-4xl font-bold">$0</span>
                                                                                                                                              <span className="text-gray-500">/forever</span>
                                                                                                                                                        </div>
                                                                                                                                                                  <ul className="space-y-3 mb-8 text-gray-600">
                                                                                                                                                                              <li className="flex items-center gap-2">
                                                                                                                                                                                            <span className="text-green-500">&#10003;</span> 3 uses per day
                                                                                                                                                                                                        </li>
                                                                                                                                                                                                                    <li className="flex items-center gap-2">
                                                                                                                                                                                                                                  <span className="text-green-500">&#10003;</span> All 50 tools
                                                                                                                                                                                                                                              </li>
                                                                                                                                                                                                                                                          <li className="flex items-center gap-2">
                                                                                                                                                                                                                                                                        <span className="text-green-500">&#10003;</span> No signup required
                                                                                                                                                                                                                                                                                    </li>
                                                                                                                                                                                                                                                                                                <li className="flex items-center gap-2">
                                                                                                                                                                                                                                                                                                              <span className="text-green-500">&#10003;</span> Copy & download results
                                                                                                                                                                                                                                                                                                                          </li>
                                                                                                                                                                                                                                                                                                                                    </ul>
                                                                                                                                                                                                                                                                                                                                              <Link
                                                                                                                                                                                                                                                                                                                                                          href="/tools"
                                                                                                                                                                                                                                                                                                                                                                      className="block w-full text-center py-3 px-6 border-2 border-blue-600 text-blue-600 rounded-lg font-medium hover:bg-blue-50 transition"
                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                            Start Free
                                                                                                                                                                                                                                                                                                                                                                                                      </Link>
                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                      {/* Pro Tier */}
                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="border-2 border-blue-600 rounded-2xl p-8 relative">
                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="absolute -top-3 left-1/2 transform -translate-x-1/2 bg-blue-600 text-white px-4 py-1 rounded-full text-sm font-medium">
                                                                                                                                                                                                                                                                                                                                                                                                                                                    Most Popular
                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <h2 className="text-2xl font-bold text-gray-900 mb-2">Pro</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="mb-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <span className="text-4xl font-bold">$19</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <span className="text-gray-500">/month</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <ul className="space-y-3 mb-8 text-gray-600">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <li className="flex items-center gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <span className="text-green-500">&#10003;</span> Unlimited uses
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <li className="flex items-center gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <span className="text-green-500">&#10003;</span> All 50 tools
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <li className="flex items-center gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <span className="text-green-500">&#10003;</span> GPT-4o premium model
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <li className="flex items-center gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <span className="text-green-500">&#10003;</span> Priority support
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <li className="flex items-center gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <span className="text-green-500">&#10003;</span> Save & history
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </ul>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button className="block w-full text-center py-3 px-6 bg-blue-600 text-white rounded-lg font-medium hover:bg-blue-700 transition">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Upgrade to Pro
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="mt-16 text-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <h3 className="text-xl font-semibold text-gray-900 mb-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Frequently Asked Questions
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="max-w-2xl mx-auto space-y-6 text-left">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <h4 className="font-medium text-gray-900">Do I need to sign up?</h4>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p className="text-gray-600 mt-1">No! Free users can use any tool without creating an account. Just pick a tool and go.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <h4 className="font-medium text-gray-900">What counts as a &quot;use&quot;?</h4>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p className="text-gray-600 mt-1">Each time you generate content with a tool counts as one use. Free users get 3 per day, which resets at midnight UTC.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <h4 className="font-medium text-gray-900">Can I cancel anytime?</h4>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p className="text-gray-600 mt-1">Yes, you can cancel your Pro subscription at any time. You will keep access until the end of your billing period.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }